### PR TITLE
turn meetup link into actual link

### PR DESCRIPTION
**Pull request by robin-drexler**
https://twitter.com/roobijn/status/459237082972815360

### CODE REVIEW

**Comment by glaubinix** [comment]
just a questions concerning this PR: would you expect the schedule to render links as clickable links or is it ok to add links manually where necessary?

**Comment by robinboehm** [comment]
Thx @robin-drexler

**Comment by robin-drexler** [comment]
@glaubinix auto detection of links would be a nice feature indeed. However, I find it more confusing that the column toggles on every click, because it prevents copying of anything inside.

**Comment by glaubinix** [comment]
@robin-drexler thanks, I will have a look at it, how we could improve the behavior.

**Pull request merged**
